# -*- coding: utf-8 -*-
"""producer_simulator.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u3Mvn6-ZJ1E1J5v7lfB-xxbUQIbJLDfF
"""

import json
import time
import pandas as pd
from datetime import datetime
import pytz
from random import uniform, randint
from kafka import KafkaProducer

# ⏰ SET INDIAN TIMEZONE
india_tz = pytz.timezone('Asia/Kolkata')

# 🧾 CONFIGURE KAFKA PRODUCER
producer = KafkaProducer(
    bootstrap_servers=['<YOUR_EC2_PUBLIC_IP>:9092'],  # Replace with EC2 public IP
    value_serializer=lambda v: json.dumps(v, default=str).encode('utf-8')
)

# 🏷️ KAFKA TOPIC NAME
TOPIC_NAME = 'stock-data-stream'

# 🧪 120 SYMBOLS
symbols = [f'SYM{i:03d}' for i in range(1, 121)]  # SYM001 to SYM120

# 🔁 CONTINUOUS SIMULATION LOOP
while True:
    current_time = datetime.now(india_tz).strftime('%Y-%m-%d %H:%M:%S')

    for symbol in symbols:
        close = round(uniform(100, 1500), 2)
        volume = randint(1000, 10000)

        stock_record = {
            "symbol": symbol,
            "Date-Time": current_time,
            "Close": close,
            "Volume": volume
        }

        # 🎯 SEND TO KAFKA
        producer.send(TOPIC_NAME, value=stock_record)

    print(f"[{current_time}] ✅ Sent batch of {len(symbols)} stock records to Kafka.")
    time.sleep(30)